services:
  - type: web
    name: voice-bot
    env: python
    pythonVersion: "3.11.9"
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_IDS
        sync: false
      - key: PORT
        value: "10000"
      - key: DEFAULT_VOICE_ID
        value: "EXAVITQu4vr4xnSDxMaL"
      - key: DEFAULT_MODEL_ID
        value: "eleven_multilingual_v2"
      - key: DATABASE_FILE
        value: "bot.db"
      - key: BROADCAST_DELAY
        value: "0.05"
    disk:
      name: bot-data
      mountPath: /opt/render/project/src
      sizeGB: 1
